### ISSUE TITLE
Handshake status 401

### ISSUE THREAD

**Issue by gfort** [MicrosoftTranslator/Python-Speech-Translate#1]
Hello,

I've tried using the basic speech.py example. I registered correctly on the marketplace to authenticate with my applications. But my problem is that I get a "Handshake status 401", and I think it's while instantiating the web socket.

Please let me know what I've done wrong.

Thanks.

Guillaume.

**Comment by kellyaltom** [comment]
Were you successfully able to get an access token?


This may help:


http://docs.microsofttranslator.com/speech-translate.html

Speech Translation API - Microsoft Translator API<http://docs.microsofttranslator.com/speech-translate.html>
docs.microsofttranslator.com
Microsoft Translator apps are designed for all of your favorite devices to translate anything, anywhere, and anytime into 50 different languages.





________________________________

**Comment by gfort** [comment]
I get a response but the token is really strange, it looks like this :  

{u'token_type': u'http://schemas.xmlsoap.org/ws/2009/11/swt-token-profile-1.0', u'access_token': u'http%3a%2f%2fschemas.xmlsoap.org%2fws%2f2005%2f05%2fidentity%2fclaims%2fnameidentifier[...]', u'expires_in': u'600', u'scope': u'http://api.microsofttranslator.com'}

**Comment by kellyaltom** [comment]
This is what a token looks like:


":"http%3a%2f%2fschemas.xmlsoap.org<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2f2fschemas.xmlsoap.org%2f&data=01%7c01%7cv-kaltom%40microsoft.com%7ce66a87dd9c7a4449614a08d38acd3c3b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=VIgirctXfv1YkcdhTdP39iJDezN0Rf4%2bwmvdaEDlK8Q%3d>%2fws%2f2005%2f05%2fidentity%2fclaims%2fnameidentifier=SmartCAT_20150724&http%3a%2f%2fschemas.microsoft.com<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2f2fschemas.microsoft.com%2f&data=01%7c01%7cv-kaltom%40microsoft.com%7ce66a87dd9c7a4449614a08d38acd3c3b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=l%2bdK2jAbmQb25ygqarp%2f6%2b0ZS7pWnml48edApI2Tuxo%3d>%2faccesscontrolservice%2f2010%2f07%2fclaims%2fidentityprovider=https%3a%2f%2fdatamarket.accesscontrol.windows.net<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2f2fdatamarket.accesscontrol.windows.net%2f&data=01%7c01%7cv-kaltom%40microsoft.com%7ce66a87dd9c7a4449614a08d38acd3c3b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=9r3lItQGk7LGxWavsyhGFoDK1wIaNlE0vxcfHqxmclQ%3d>%2f&Audience=http%3a%2f%2fapi.microsofttranslator.com<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2f2fapi.microsofttranslator.com%2f&data=01%7c01%7cv-kaltom%40microsoft.com%7ce66a87dd9c7a4449614a08d38acd3c3b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=%2fZm%2bHqpeJjgmbUZXQ0qPU2wMCRQHa2iWKpbblD%2fEvd8%3d>&ExpiresOn=1464713718&Issuer=https%3a%2f%2fdatamarket.accesscontrol.windows.net<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2f2fdatamarket.accesscontrol.windows.net%2f&data=01%7c01%7cv-kaltom%40microsoft.com%7ce66a87dd9c7a4449614a08d38acd3c3b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=9r3lItQGk7LGxWavsyhGFoDK1wIaNlE0vxcfHqxmclQ%3d>%2f&HMACSHA256=hoKZ2M5xzqy5PKWDL%2fVCNqHzFoH5joqHwpOaUSBByd0%3d","expires_in":"600","scope":"http://api.microsofttranslator.com"<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fapi.microsofttranslator.com%2f&data=01%7c01%7cv-kaltom%40microsoft.com%7ce66a87dd9c7a4449614a08d38acd3c3b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=L9IKWu1fxmKG7C%2bAIfJB%2fQrlbPTw6Szyyr1gAUmFnHc%3d>

Some problems people run into sometimes:

The client secret should end with an "="

The word "Bearer " needs to be added at the beginning of the token.

Kelly
________________________________

**Comment by kellyaltom** [comment]
The previous post copied the token 3 times, not sure why it did that.
This is what a token looks like:

":"http%3a%2f%2fschemas.xmlsoap.org%2fws%2f2005%2f05%2fidentity%2fclaims%2fnameidentifier=SmartCAT_20150724&http%3a%2f%2fschemas.microsoft.com%2faccesscontrolservice%2f2010%2f07%2fclaims%2fidentityprovider=https%3a%2f%2fdatamarket.accesscontrol.windows.net%2f&Audience=http%3a%2f%2fapi.microsofttranslator.com&ExpiresOn=1464713718&Issuer=https%3a%2f%2fdatamarket.accesscontrol.windows.net%2f&HMACSHA256=hoKZ2M5xzqy5PKWDL%2fVCNqHzFoH5joqHwpOaUSBByd0%3d","expires_in":"600","scope":"http://api.microsofttranslator.com"

**Comment by manishth** [comment]
@kellyaltom I am getting the same issue, I tried this solution but it didn't work, I still get the error "Handshake status 401 Unauthorized", is this solution still relevant?
