### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by jhoelzl** [MicrosoftTranslator/Python-Speech-Translate#3]
Hello,

when i run `speech.py` i get this error:

> Traceback (most recent call last):
  File "speech.py", line 115, in <module>
    print(adm_client.get_access_token())
  File "/media/user/data/lm-tools/Python-Speech-Translate/adm.py", line 39, in get_access_token
    response.raise_for_status()
  File "/media/user/data/lm-tools/Python-Speech-Translate/venv/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://datamarket.accesscontrol.windows.net/v2/OAuth2-13

In the Python script, i adjusted the values for `client_id` and `client_secret`, however, i am not quite sure which keys i have to copy from the Azure Portal.

Now, i used the **subscription-key** from Azure Portal subscription with APi type `Translator Speech API` for `client_id` and **key 1 or key 2** from Azure Portal for `client_secret`. Is this correct? The

**Comment by kellyaltom** [comment]
Hi,


The move away from clientID and clientsecret, to an azure key also means a change in the call to get a token.


The endpoint changes when you get a token with an azure key, and some the parameters in the header are removed.


You can find out the differences at: http://docs.microsofttranslator.com/oauth-token.html


You can also try out the token method at this site

Cognitive Services - OAuth Token<http://docs.microsofttranslator.com/oauth-token.html>
docs.microsofttranslator.com
Documentation Authentication Token API. Authentication Token API; Text Translation API; Speech Translation API; Speech Translation API - Languages




________________________________

**Comment by jhoelzl** [comment]
@kellyaltom thank you, i replaced the function `adm_client.get_access_token()` in https://github.com/MicrosoftTranslator/Python-Speech-Translate/blob/master/speech.py#L222 with my own token string generated from http://docs.microsofttranslator.com/oauth-token.html and now it works.

So `speech.py` should be updated.
